# Site settings
title: Anil Nautiyal
twitter_username: anilnautiyal
name: Anil Nautiyal

# Build settings

#User specific content
#Links that will appear in the navbar
primarylinks:

 - title: GitHub
   url: https://github.com/anilnautiyal
   
#Any buzzword skills you want to include
skills:
 - GitHub CI/CD
 - Jenkind
 - AWS Services
 - Linux Server (Centos, Ubuntu) hosting knowledge
 - SSL Implementation
 - Knowledge of DNS configuration
 - Knowledge of PHP
 - Website Hosting knowledge of Wordpress, Laravel, Codignator, Magento.
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list

#Work experience is required
roles:
 - title: Sr. DevOps Engineer  
   start: 2019
   end: Ongoing
   employer: Bamko India
   description: Working on DevOps tools: Github CI/CD, Jenkins, AWS, New Relic, Sucuri WAF.
 - title: Network/Server Support and DevOps Engineer
   start: 2012
   end: 2019
   employer: Rubico IT Pvt Ltd 
   description: Experienced in DevOps tools: Github CI/CD, Jenkins, AWS, New Relic, Sucuri WAF, DNS, TCP/IP, SSL, Wi-Fi Security with DD-Wrt firmware.
 - title: Executive-IT-Support
   start: 2011
   end: 2012
   employer: Acropolis Research Services
   description: Experienced in Server Windows, Linux(Centos, Ubuntu, Mac), LAMP Support 
 - title: Network Engineer
   start: 2010
   end: 2011
   employer: HCL Infosystems Ltd.
   description: Experienced in Server Windows, Linux(Centos, Ubuntu, Mac), Router and Switches Configuration (Juniper, Cisco) 

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham
   
#Education is required
education:
 - level: Master Of Computer Application (MCA)
   date: 2009
   subject: Computer Languages and Nerworking
   school: IMS Dehradum, Uttarakhand Technical University 
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2006
   subject: Physics, Chemistry, Mathematics
   school: D.B.S (PG) College Dehradun, HNB Garhwal University
   
#Education is required
education:
 - level: 12th
   date: 2003
   subject: Physics, Chemistry, Mathematics, English, Hindi
   school: GIC (GD) Ghansali, Tehri Garhwal
   
#Education is required
education:
 - level: 10th
   date: 2001
   subject: Science, Mathematics, English, Hindi, Commerce
   school: GIC (GD) Ghansali, Tehri Garhwal

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute

#List of interesting Github repo/projects to include - optional
github:
 - anilnautiyal/anilnautiyal.github.io

#Stackoverflow flair is optional

intro: |
  I am an engineer with 8 years experience working in DevOps technology. I have primarily worked on DevOps tools.
  I enjoy building interesting scripts for the auto-deploymen.
 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
